version: "3.8"

services:
  db:
    env_file:
      - .env
    build:
      context: .
      dockerfile: dockerfile.mysql
      args:
        - IMAGE_TAG=${MYSQL_IMAGE_TAG}
    ports:
      - "3306:3306"
    container_name: sylius_db
  sylius:
    env_file:
      - .env
    build:
      context: .
      dockerfile: dockerfile.sylius
      args:
        - IMAGE_TAG=${SYLIUS_IMAGE_TAG}
        - HOST_IP=${HOST_IP}
    volumes:
      - ./shop:/var/www/html/shop:rw
    container_name: sylius_dev
    depends_on:
      - db

